SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_OFFSET_LIMIT = 250
SCREEN_ACCELERATION = 50
SCREEN_DEACCELERATION = 10

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = .8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 5
ASTEROID_MAX_SPEED = 20
ASTEROID_LIFETIME = 60
ASTEROID_MAX_ROTATION_SPEED = 300

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 800
PLAYER_ACCELERATION = 200
PLAYER_DEACCELERATION = 200

BACKGROUND_MIN_STARS = 15
BACKGROUND_MAX_STARS = 25
BACKGROUND_LAYERS = 6
BACKGROUND_SPEED_MULTIPLIER = .1
