SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_OFFSET_LIMIT = 250
SCREEN_ACCELERATION = 50
SCREEN_DEACCELERATION = 30

ASTEROID_MIN_RADIUS = 20
ASTEROID_MIN_RADIUS_SPAN = 10
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = .8
ASTEROID_CHILD_DIVIDER = 8
ASTEROID_CHILD_VELOCITY_MULTIPLIER = 10
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 5
ASTEROID_MAX_SPEED = 100
ASTEROID_LIFETIME = 60
ASTEROID_MAX_ROTATION_SPEED = 300
ASTEROID_COLOR = "#eed49f"
ASTEROID_THICKNESS = 5
ASTEROID_GROW_SPEED = 100
ASTEROID_SHRINK_SPEED = 500

ASTEROID_EXPLOSION_RADIUS = 10
ASTEROID_EXPLOSION_LIFETIME = .1
ASTEROID_EXPLOSION_EXPAND_RATE = 2000
ASTEROID_EXPLOSION_MAX_JITTER = 6
ASTEROID_EXPLOSION_COLOR = "#f5a97f"
ASTEROID_EXPLOSION_THICKNESS = 2
ASTEROID_EXPLOSION_MIN_NUM_POINTS = 12
ASTEROID_EXPLOSION_MAX_NUM_POINTS = 32

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 800
PLAYER_ACCELERATION = 200
PLAYER_DEACCELERATION = 200
PLAYER_FIRE_RATE = 0.2
PLAYER_COLOR = "#f5bde6"
PLAYER_THICKNESS = 2
PLAYER_REAR_THRUST_COLOR = "#f5a97f"
PLAYER_REAR_THRUST_THICKNESS = 2
PLAYER_REAR_THRUST_FLAME_UPDATE_RATE = .1
PLAYER_REAR_THRUST_FLAME_PADDING = 7

BACKGROUND_MIN_STARS = 15
BACKGROUND_MAX_STARS = 25
BACKGROUND_LAYERS = 6
BACKGROUND_SPEED_MULTIPLIER = .1
BACKGROUND_STAR_DISTORTION_LIMIT = 200
BACKGROUND_STAR_DISTORTION_MAX_LENGTH = 0.05
BACKGROUND_STAR_COLOR = "#cad3f5"
BACKGROUND_COLOR = "#181926"

LASER_LIFETIME = 0.05
LASER_COLOR = "#ed8796"
LASER_MAX_LENGTH = 500
LASER_WIDTH = 5
LASER_AIM_ASSIST_DEGREE = 30

SCORE_MULTIPLIER = 10

UI_OFFSET = 30
UI_SCORE_WIDTH = SCREEN_WIDTH - (UI_OFFSET * 2)
UI_SCORE_HEIGHT = 10
UI_COLOR = "#87B0F9"

LEVEL_LIMIT = 10

DEBUG_ENABLED = False

FONT_REGULAR = "fonts/1.ttf"
FONT_BOLD = "fonts/2.ttf"
FONT_SIZE = 42
